"""Typed shapes — CrossSpaceRequest / CrossSpaceReceipt.

The envelope deliberately does NOT carry origin conversation, origin
reasoning trace, or origin agent's situation context. Bounded by
design — target sees only the request capsule (action_kind +
work_order + provenance).
"""
from __future__ import annotations

import uuid
from dataclasses import dataclass, field
from typing import Any, Literal


# ---------------------------------------------------------------------------
# Action kind whitelist — v1
# ---------------------------------------------------------------------------

ALLOWED_ACTION_KINDS: frozenset[str] = frozenset({
    "write_knowledge",
    "propose_covenant",
    "create_plan_draft",
    "create_workflow_draft",
})


ReceiptStatus = Literal[
    "completed",
    "proposed",
    "needs_confirmation",
    "refused",
    "failed",
]


# ---------------------------------------------------------------------------
# Envelope: agent → kernel
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class CrossSpaceRequest:
    """The bounded capsule the kernel runs against the target space.

    No origin conversation / reasoning trace fields — by design.
    Target sees only what's needed to evaluate covenants, dispatch,
    and audit.
    """

    request_id: str                # idempotency key, generated by origin
    origin_space_id: str
    target_space_id: str
    initiating_member_id: str
    source_turn_id: str
    action_kind: str               # one of ALLOWED_ACTION_KINDS
    work_order: dict[str, Any]     # structured per action_kind
    instance_id: str               # in-instance only for v1
    safety_class: str = "default"  # informational; routes audit category


@dataclass(frozen=True)
class CrossSpaceReceiptRef:
    """One ref into target state created by the request."""

    type: str                      # "knowledge_entry" | "covenant_proposal" | "plan_draft" | "workflow_draft"
    id: str


@dataclass(frozen=True)
class CrossSpaceReceipt:
    """Kernel → origin agent. Returned as the tool result.

    The agent can paraphrase ``user_visible_summary`` in its voice or
    surface verbatim. ``refusal_reason`` is populated only when
    ``status == 'refused'`` or ``'failed'``.
    """

    request_id: str
    status: ReceiptStatus
    target_space_id: str
    timestamp: str
    created_refs: tuple[CrossSpaceReceiptRef, ...] = ()
    target_audit_ref: str = ""
    provenance: dict[str, Any] = field(default_factory=dict)
    user_visible_summary: str = ""
    refusal_reason: str = ""

    def to_tool_result(self) -> dict[str, Any]:
        """Serialize to the JSON-shaped dict returned through the
        agent's tool-result channel."""
        return {
            "request_id": self.request_id,
            "status": self.status,
            "target_space_id": self.target_space_id,
            "timestamp": self.timestamp,
            "created_refs": [
                {"type": r.type, "id": r.id} for r in self.created_refs
            ],
            "target_audit_ref": self.target_audit_ref,
            "provenance": dict(self.provenance),
            "user_visible_summary": self.user_visible_summary,
            "refusal_reason": self.refusal_reason,
        }


def new_request_id() -> str:
    """Generate a UUID-shaped request_id. Origin agents may pass
    their own (e.g. for testing); production callers use this."""
    return f"csr_{uuid.uuid4().hex[:16]}"


__all__ = [
    "ALLOWED_ACTION_KINDS",
    "CrossSpaceReceipt",
    "CrossSpaceReceiptRef",
    "CrossSpaceRequest",
    "ReceiptStatus",
    "new_request_id",
]
